SMS/src/java/entities/Poruke.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Grupa1
 */
@Entity
@Table(name = "poruke")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Poruke.findAll", query = "SELECT p FROM Poruke p")
    , @NamedQuery(name = "Poruke.findById", query = "SELECT p FROM Poruke p WHERE p.id = :id")
    , @NamedQuery(name = "Poruke.findByTekst", query = "SELECT p FROM Poruke p WHERE p.tekst = :tekst")
    , @NamedQuery(name = "Poruke.findByPosiljalacId", query = "SELECT p FROM Poruke p WHERE p.posiljalac = :posiljalac")
    , @NamedQuery(name = "Poruke.findByPrimalacId", query = "SELECT p FROM Poruke p WHERE p.primalac = :primalac")})
public class Poruke implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "tekst")
    private String tekst;
    @JoinColumn(name = "posiljalac", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Korisnici posiljalac;
    @JoinColumn(name = "primalac", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Korisnici primalac;

    public Poruke() {
    }

    public Poruke(Integer id) {
        this.id = id;
    }

    public Poruke(Integer id, String tekst) {
        this.id = id;
        this.tekst = tekst;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTekst() {
        return tekst;
    }

    public void setTekst(String tekst) {
        this.tekst = tekst;
    }

    public Korisnici getPosiljalac() {
        return posiljalac;
    }

    public void setPosiljalac(Korisnici posiljalac) {
        this.posiljalac = posiljalac;
    }

    public Korisnici getPrimalac() {
        return primalac;
    }

    public void setPrimalac(Korisnici primalac) {
        this.primalac = primalac;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Poruke)) {
            return false;
        }
        Poruke other = (Poruke) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Poruke[ id=" + id + " ]";
    }
    
}

SMS/src/java/entities/Ucitelji.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Grupa2
 */
@Entity
@Table(name = "ucitelji")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Ucitelji.findAll", query = "SELECT u FROM Ucitelji u")
    , @NamedQuery(name = "Ucitelji.findById", query = "SELECT u FROM Ucitelji u WHERE u.id = :id")
    , @NamedQuery(name = "Ucitelji.findByIme", query = "SELECT u FROM Ucitelji u WHERE u.ime = :ime")
    , @NamedQuery(name = "Ucitelji.findByPrezime", query = "SELECT u FROM Ucitelji u WHERE u.prezime = :prezime")
    , @NamedQuery(name = "Ucitelji.findByKorisniciId", query = "SELECT u FROM Ucitelji u WHERE u.korisniciId = :id")})
public class Ucitelji implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "ime")
    private String ime;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "prezime")
    private String prezime;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "uciteljiId")
    private List<Odeljenja> odeljenjaList;
    @JoinColumn(name = "korisnici_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Korisnici korisniciId;

    public Ucitelji() {
    }

    public Ucitelji(Integer id) {
        this.id = id;
    }

    public Ucitelji(Integer id, String ime, String prezime) {
        this.id = id;
        this.ime = ime;
        this.prezime = prezime;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIme() {
        return ime;
    }

    public void setIme(String ime) {
        this.ime = ime;
    }

    public String getPrezime() {
        return prezime;
    }

    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    @XmlTransient
    public List<Odeljenja> getOdeljenjaList() {
        return odeljenjaList;
    }

    public void setOdeljenjaList(List<Odeljenja> odeljenjaList) {
        this.odeljenjaList = odeljenjaList;
    }


    public Korisnici getKorisniciId() {
        return korisniciId;
    }

    public void setKorisniciId(Korisnici korisniciId) {
        this.korisniciId = korisniciId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Ucitelji)) {
            return false;
        }
        Ucitelji other = (Ucitelji) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Ucitelji[ id=" + id + " ]";
    }
    
}

SMS/src/java/managedBeans/CasoviManagedBean.java
package managedBeans;

import business.sessionBeans.CasoviSessionBeanLocal;
import entities.Casovi;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name ="casoviMB")
@SessionScoped
public class CasoviManagedBean implements Serializable{
    
    @EJB
    private CasoviSessionBeanLocal casoviBean;
    
    public List<Casovi> getAllCasovi() {
        
        return casoviBean.getAllCasovi();
    }
}

SMS/src/java/managedBeans/OceneManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBeans;

import business.sessionBeans.OceneSessionBeanLocal;
import business.sessionBeans.StudentSessionBeanLocal;
import entities.Ocene;
import entities.Ucenici;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Grupa1
 */
@ManagedBean(name = "oceneMB", eager = true)
@SessionScoped
public class OceneManagedBean implements Serializable{

    @EJB
    private OceneSessionBeanLocal oceneBean; 
    @EJB
    private StudentSessionBeanLocal studentBean; 
    
    private Integer ucenik;
    
    FacesContext facesContext = FacesContext.getCurrentInstance();
    StudentManagedBean studentMB = (StudentManagedBean)facesContext.getApplication()
      .createValueBinding("#{studentMB}").getValue(facesContext);
    
    public OceneManagedBean() {
        
    }
    public List<Ocene> getOceneUcenika(){ 
        Ucenici ucenici = studentBean.getStudentWhereId(Integer.parseInt(FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("ucenik")));
        setUcenik(ucenici.getId());
        return oceneBean.getOceneUcenika(getUcenik());
    }
    public List<Ocene> getOceneWherePredmet(){
        Ucenici ucenici = studentBean.getStudentWhereId(Integer.parseInt(FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("ucenik")));
        setUcenik(ucenici.getId());
        
        return oceneBean.getOceneWhereUcenikAndPredmet(getUcenik(), ucenik);
        
    }

    /**
     * @return the ucenik
     */
    public Integer getUcenik() {
        return ucenik;
    }

    /**
     * @param ucenik the ucenik to set
     */
    public void setUcenik(Integer ucenik) {
        this.ucenik = ucenik;
    }
    
    
}

SMS/src/java/managedBeans/ParentManagedBean.java
package managedBeans;

import business.sessionBeans.ParentSessionBeanLocal;
import entities.Roditelji;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "parentsMB", eager = true)
@SessionScoped
public class ParentManagedBean implements Serializable{
    
    @EJB
    private ParentSessionBeanLocal parentsBean;

    public List<Roditelji> getAllParents() {
        
        return parentsBean.getAllParents();        
    }
}

SMS/src/java/managedBeans/StudentManagedBean.java
package managedBeans;

import business.sessionBeans.DepartmentSessionBeanLocal;
import business.sessionBeans.StudentSessionBeanLocal;
import business.sessionBeans.UciteljiSessionBeanLocal;
import entities.Ucenici;
import entities.Ucitelji;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "studentMB", eager = true)
@SessionScoped
public class StudentManagedBean implements Serializable{
    
    private Integer odeljenje = null;
    @ManagedProperty("#{ucenik}")
    private Integer ucenik = null;
    
    private Ucenici chosenUcenik;
    
    @EJB
    private StudentSessionBeanLocal studentBean;
    @EJB
    private DepartmentSessionBeanLocal departmentBean;
    @EJB
    private UciteljiSessionBeanLocal uciteljiBean;
    
    FacesContext facesContext = FacesContext.getCurrentInstance();
    LoginManagedBean loginMB = (LoginManagedBean)facesContext.getApplication()
      .createValueBinding("#{loginMB}").getValue(facesContext);
    
    public List<Ucenici> getAllStudents() {
        
        return studentBean.getAllStudents();
    }
        public List<Ucenici> getAllStudentsFromDepartment() {
        Ucitelji ucitelji = uciteljiBean.getUciteljByKorisniciId(loginMB.getLoggedInUser().getId());
        setOdeljenje(departmentBean.getDepartmentWhereUciteljiId(ucitelji.getId()).getId());
        return studentBean.getStudentsFromDepartment(getOdeljenje());
    }

    /**
     * @return the odeljenje
     */
    public Integer getOdeljenje() {
        return odeljenje;
    }

    /**
     * @param odeljenje the odeljenje to set
     */
    public void setOdeljenje(Integer odeljenje) {
        this.odeljenje = odeljenje;
    }

    /**
     * @return the ucenik
     */
    public Integer getUcenik() {
        return ucenik;
    }

    /**
     * @param ucenik the ucenik to set
     */
    public void setUcenik(Integer ucenik) {
        this.ucenik = ucenik;
    }

    /**
     * @return the chosenUcenik
     */
    public Ucenici getChosenUcenik() {
        return chosenUcenik;
    }

    /**
     * @param chosenUcenik the chosenUcenik to set
     */
    public void setChosenUcenik(Ucenici chosenUcenik) {
        this.chosenUcenik = chosenUcenik;
    }
}

SMS/web/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h2>Lista odeljenja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id= "odeljenjaId" value= "#{departmentMB.departments}" var= "odeljenje">
                <h:column>
                    <f:facet name="header">Učitelj</f:facet>
                        #{odeljenje.uciteljiId.ime} #{odeljenje.uciteljiId.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet> 
                        #{odeljenje.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Izmena</f:facet>
                    <h:commandButton value='Izmeni'/>
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        
        <h2>Lista ucenika:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "uceniciId" value="#{studentMB.allStudents}" var="ucenici">
                <h:column>
                    <f:facet name="header">Učenik</f:facet>
                        #{ucenici.ime} #{ucenici.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>    
                    <f:facet name="header">Odeljenje</f:facet>
                        #{ucenici.odeljenjaId.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>   
                    <f:facet name="header">Roditelj</f:facet>
                        #{ucenici.roditeljiId.ime} #{ucenici.roditeljiId.prezime}
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        
        <h2>Lista roditelja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "roditeljiId" value="#{parentsMB.allParents}" var="roditelji">
                <h:column>
                    <f:facet name="header">Roditelj</f:facet>
                        #{roditelji.ime} #{roditelji.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>    
                    <f:facet name="header">Nalog</f:facet>
                        #{roditelji.korisniciId.nalog}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>   
                    <f:facet name="header">Loznka</f:facet>
                       #{roditelji.korisniciId.lozinka}
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        <h:form>
            <h:link value="Prijava" outcome="index"/>
        </h:form>
    </h:body>
</html>

SMS/web/raspored.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Raspored</title>
    </h:head>
    <h:body>
        <h:form id="kreiranjeRasporeda"> 
            <h3><h:outputLabel value="KREIRANJE RASPOREDA"/><hr/></h3><br/>
            <h:outputLabel value="Izaberi odeljenje:"/>
            <br/>
            <h:dataTable value="#{casoviMB.allCasovi}" var="c" border="1">
                <h:column>
                    <f:facet name="header">Čas</f:facet>
                    #{c.broj}
                </h:column>
                <h:column>
                    <f:facet name="header">Ponedeljak</f:facet>
                    <h:selectOneMenu> 
                        <f:selectItem itemValue="1" itemLabel="Matematika" />
                        <f:selectItem itemValue="2" itemLabel="Srpski" />
                        <f:selectItem itemValue="3" itemLabel="Engleski" />
                        <f:selectItem itemValue="4" itemLabel="Likovno" />      
                        <f:selectItem itemValue="5" itemLabel="Fizicko" />
                    </h:selectOneMenu>
                </h:column>
                <h:column>
                    <f:facet name="header">Utorak</f:facet> 
                    <h:selectOneMenu> 
                        <f:selectItem itemValue="1" itemLabel="Matematika" />
                        <f:selectItem itemValue="2" itemLabel="Srpski" />
                        <f:selectItem itemValue="3" itemLabel="Engleski" />
                        <f:selectItem itemValue="4" itemLabel="Likovno" />      
                        <f:selectItem itemValue="5" itemLabel="Fizicko" />
                    </h:selectOneMenu>
                </h:column>
                <h:column>
                    <f:facet name="header">Sreda</f:facet>
                    <h:selectOneMenu> 
                        <f:selectItem itemValue="1" itemLabel="Matematika" />
                        <f:selectItem itemValue="2" itemLabel="Srpski" />
                        <f:selectItem itemValue="3" itemLabel="Engleski" />
                        <f:selectItem itemValue="4" itemLabel="Likovno" />      
                        <f:selectItem itemValue="5" itemLabel="Fizicko" />
                    </h:selectOneMenu>    
                </h:column>
                <h:column>
                    <f:facet name="header">Četvrtak</f:facet>
                    <h:selectOneMenu> 
                        <f:selectItem itemValue="1" itemLabel="Matematika" />
                        <f:selectItem itemValue="2" itemLabel="Srpski" />
                        <f:selectItem itemValue="3" itemLabel="Engleski" />
                        <f:selectItem itemValue="4" itemLabel="Likovno" />      
                        <f:selectItem itemValue="5" itemLabel="Fizicko" />
                    </h:selectOneMenu>    
                </h:column>
                <h:column>
                    <f:facet name="header">Petak</f:facet>
                    <h:selectOneMenu> 
                        <f:selectItem itemValue="1" itemLabel="Matematika" />
                        <f:selectItem itemValue="2" itemLabel="Srpski" />
                        <f:selectItem itemValue="3" itemLabel="Engleski" />
                        <f:selectItem itemValue="4" itemLabel="Likovno" />      
                        <f:selectItem itemValue="5" itemLabel="Fizicko" />
                    </h:selectOneMenu>
                </h:column>
            </h:dataTable><br/>
            
            <h:commandButton value="SNIMI"/>
        </h:form><hr/>
        <h:form id="brisanjeRasporeda">
            <h3><h:outputLabel value="BRISANJE RASPOREDA"/></h3><hr/>
            <h:outputLabel value="Izaberi odeljenje za brisanje rasporeda:"/>
            <h:selectOneMenu>
                
            </h:selectOneMenu>
            <br/>
            <h:commandButton value="OBRIŠI"/>
        </h:form>
    </h:body>
</html>

SMS/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Elektronski dnevnik - Registracija</title>
    </h:head>
    <h:body>
        <h2>Registracija učenika:</h2>
        <hr/>
        <h:form>
            <h:outputLabel value="Izaberite roditelja: "/><br/>
            <h:dataTable id= "roditelji" value= "#{parentsMB.allParents}" var= "p" border="1">
                <h:column>
                    <f:facet name="header">Ime i prezime</f:facet>
                        #{p.ime} #{p.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Dodaj učenika</f:facet>
                    <h:commandButton value="Dodaj"/>
                </h:column>
            </h:dataTable>
            <h:dataTable id= "registracija" value="#{registerMB}" var="reg">
                <h:column>
                    <f:facet name="header">Ime</f:facet>
                    <h:inputText id="ime" required="true" p:placeholder="Ime" requiredMessage="Polje je obavezno!" value="#{registerMB.name}" /> 
                    <br/><h:message for="ime"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Prezime</f:facet>
                    <h:inputText id="prezime" required="true" p:placeholder="Prezime" requiredMessage="Polje je obavezno!" value="#{registerMB.surname}" /> 
                    <br/><h:message for="prezime"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet>
                    <h:inputText id="odeljenje" required="true" p:placeholder="Odeljenje" requiredMessage="Polje je obavezno!" value="#" /> 
                    <br/><h:message for="odeljenje"/>
                </h:column>              
                <h:column>
                    <f:facet name="header"/>
                    <h:commandButton value="Dodaj"/>
                </h:column>
            </h:dataTable>
        </h:form>
        
        <h2>Registracija korisnika:</h2>
        <hr/>
        <h:form>
            <h:panelGrid id = "registracijaId" columns = "3" cellpadding = "10" cellspacing = "1">
                <h:outputLabel value = "Ime:" />
                <h:inputText id="ime" required="true" p:placeholder="Ime" requiredMessage="Polje je obavezno!" value="#{registerMB.name}" />
                <h:message for="ime" />
                
                <h:outputLabel value = "Prezime:" />
                <h:inputText id="prezime" required="true" p:placeholder="Prezime" requiredMessage="Polje je obavezno!" value="#{registerMB.surname}" />                                                                                                                                
                <h:message for="prezime" />
                
                <h:outputLabel value = "Nalog:" />
                <h:inputText id="nalog" required="true" p:placeholder="Nalog" requiredMessage="Polje je obavezno!" value="#{registerMB.username}" />
                <h:message for="nalog" />
                
                <h:outputLabel value = "Lozinka:" />
                <h:inputSecret id="lozinka" required="true" p:placeholder="Lozinka" requiredMessage="Polje je obavezno!" value="#{registerMB.password}" />
                <h:message for="lozinka" />
            </h:panelGrid>
 
            <h:panelGrid id = "user" columns = "5" cellpadding = "10" cellspacing = "1">
                <h:selectOneRadio id="radio" required="true" requiredMessage="Obavezno izabrati korisnika!" value="#{registerMB.user}">
                    <f:selectItem itemLabel="Admin" itemValue="0"/>
                    <f:selectItem itemLabel="Direktor" itemValue="1"/>
                    <f:selectItem itemLabel="Učitelj" itemValue="2"/>
                    <f:selectItem itemLabel="Roditelj" itemValue="3"/>
                </h:selectOneRadio>
                <h:message for="radio" />
            </h:panelGrid>
                <div name="footerRegister">
                    <h:panelGrid>
                        <f:facet name="footer">
                            <h:commandButton id="registrujSe" value="Registruj" action="#{registerMB.register()}" />
                        </f:facet>
                    </h:panelGrid>
                </div>
            <h2>Lista odeljenja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id= "odeljenjaId" value= "#{departmentMB.departments}" var= "odeljenje" border="1">
                <h:column>
                    <f:facet name="header">Učitelj</f:facet>
                        #{odeljenje.uciteljiId.ime} #{odeljenje.uciteljiId.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet> 
                        #{odeljenje.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Izmena</f:facet>
                    <h:commandButton value='Izmeni'/>
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        
        <h2>Lista ucenika:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "uceniciId" value="#{studentMB.allStudents}" var="ucenici" border="1">
                <h:column>
                    <f:facet name="header">Učenik</f:facet>
                        #{ucenici.ime} #{ucenici.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>    
                    <f:facet name="header">Odeljenje</f:facet>
                        #{ucenici.odeljenjaId.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>   
                    <f:facet name="header">Roditelj</f:facet>
                        #{ucenici.roditeljiId.ime} #{ucenici.roditeljiId.prezime}
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        
        <h2>Lista roditelja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "roditeljiId" value="#{parentsMB.allParents}" var="roditelji" border="1">
                <h:column>
                    <f:facet name="header">Roditelj</f:facet>
                        #{roditelji.ime} #{roditelji.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>    
                    <f:facet name="header">Nalog</f:facet>
                        #{roditelji.korisniciId.nalog}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>   
                    <f:facet name="header">Loznka</f:facet>
                       #{roditelji.korisniciId.lozinka}
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        <h:form>
            <h:link value="Prijava" outcome="index"/>
        </h:form>
        </h:form> 
    </h:body>
</html>